### PR TITLE
Make adding vendor requests easier

### PR DESCRIPTION
**Pull request by docprofsky**
This makes it much easier to add vendor requests before the end, as
each vendor request is based on the one before it. So only the request immediately after the added one has to change.

### CODE REVIEW

**Comment by dominicgs** [comment]
This makes it much harder to reconcile the lists in the Python module and the C code (for both firmware and host code)

**Comment by docprofsky** [comment]
I made it better.

**Comment by dominicgs** [comment]
Go on then, I can get on board with this version

**Comment by docprofsky** [comment]
You can get on _board_?

**Pull request merged**
